### ISSUE TITLE
共通タイトルバーを作る

### ISSUE THREAD

**Issue by uma0628** [k-mopi/your-office#12]

**Comment by uma0628** [comment]
- component: TitleBarComponent

**Comment by uma0628** [comment]
- パラメータで渡されたタイトルを表示する

**Comment by yanagita26** [comment]
実装しました。
問題があればリオープンしてください。

**Comment by KadoTomohiro** [comment]
背景色をメニューと合わせてください

`  background-color: #0981C1;`

**Comment by yanagita26** [comment]
共通カラーを適応し、developにマージしました。
