### ISSUE TITLE
テキストボックスを作る

### ISSUE THREAD

**Issue by uma0628** [k-mopi/your-office#15]

**Comment by uma0628** [comment]
- typeはパラメータで渡す
- テキストボックス上部にラベル表示。ラベル名はパラメータで渡す
- 必須項目の場合は「＊」を出す。出すかどうかはパラメータで渡す。
- テキストボックス下部にバリデーションエラーの際のラベル表示
- 必須項目の場合、テキストボックスが空の時は「必須項目です」
- 不正な値が設定されている場合は「不正な値です」
- 複数項目チェック（借方・貸方の金額チェックなど）のときは？？

**Comment by uma0628** [comment]
- shared/input配下にコンポーネントは作成する

**Comment by uma0628** [comment]
- component: TextboxComponent

**Comment by yanagita26** [comment]
実装しました。
問題があればリオープンしてください。
