### ISSUE TITLE
共通ヘッダを作る

### ISSUE THREAD

**Issue by uma0628** [k-mopi/your-office#8]

**Comment by uma0628** [comment]
- component: HeaderComponent

**Comment by uma0628** [comment]
- ユーザー情報が無ければ、ログイン画面に遷移
- ユーザー情報があれば、ユーザー名を表示
- 画面タイトルを表示する

**Comment by KadoTomohiro** [comment]
ログイン画面に遷移はヘッダの機能ではないので、別で実装します。
